title: My Blog
description: "Notes on CS, running, and whatever else"
url: "http://localhost:4000"
baseurl: "/digitalgarden"

markdown: kramdown
permalink: /:year/:month/:day/:title/

theme: minima

plugins:
  - jekyll-feed

exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - README.md

timezone: Asia/Ho_Chi_Minh
