title: My Blog
description: "Notes on CS, running, and whatever else"
url: "http://localhost:4000"
baseurl: ""

email: "hai.nguyen.phc@gmail.com"

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Remove or comment out, as it conflicts with remote_theme.
# theme: minima
# With jekyll-remote-theme plugin enabled.
remote_theme: jekyll/minima

exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - README.md

timezone: Asia/Ho_Chi_Minh

sass:
  quiet_deps: true
  silence_deprecations: ["import", "color-functions", "global-builtin"]

collections:
  projects:
    output: true
    permalink: /projects/:path/
  notes:
    output: true
    permalink: /notes/:categories/:path/
  life:
    output: true
    permalink: /life/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
  - scope:
      path: ""
      type: "life"
    values:
      layout: "life"
